version: '3.8'

services:
  app:
    build: .
    ports:
      - "8182:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=trabalho_volo
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "8183:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trabalho_volo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 