name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/trabalho-volo:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 201.23.3.86
        username: aluno
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/trabalho-volo:latest
          docker stop trabalho-volo || true
          docker rm trabalho-volo || true
          docker network create trabalho-network || true
          docker run -d \
            --name postgres-trabalho \
            --network trabalho-network \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=trabalho_volo \
            postgres:14-alpine || true
          sleep 10
          docker run -d \
            --name trabalho-volo \
            --network trabalho-network \
            -p 8182:8182 \
            -e PORT=8182 \
            -e DB_HOST=postgres-trabalho \
            -e DB_PORT=5432 \
            -e DB_USER=postgres \
            -e DB_PASSWORD=postgres \
            -e DB_NAME=trabalho_volo \
            ${{ secrets.DOCKER_HUB_USERNAME }}/trabalho-volo:latest 